version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4510-4530:4510-4530"
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-s3}
      - DEBUG=${DEBUG-}
